### DISCUSSION TITLE
Livewire stops working after five minutes on production

### DISCUSSION THREAD

**Discussion by mohsenbostan** [livewire/livewire#4284] [1. Help]
Hi.
On my local system, Livewire runs without any issues. However, on the production server, when I start the Docker container, it works fine for about 5 minutes, but after that, Livewire components stop working.
When I click on a button to edit a Model data or select an option from the select box, it won't work, and I get the following error in my console:

```
Uncaught (in promise) SyntaxError: Unexpected token { in JSON at position 581
    at JSON.parse (<anonymous>)
    at index.js:58
``` 

Here is the response from the Livewire request, which appears to have been damaged:

![image](https://user-images.githubusercontent.com/20592417/143502555-1f36fe6b-6b55-44d6-976a-2935279dd136.png)

 - Laravel version : ^8.40
 - Livewire version : ^2.5
 - PHP version : 8.0.9-fpm
 - web server : Nginx

**Comment by joshhanley** [comment]
@mohsenbostan hmm that's strange. Maybe there is some form of session timeout or something happening (although Livewire has support for detecting that)?

It seems like it's not returning a JSON response properly, instead just being text or something. Can you send a screenshot of some of the other tabs (headers and payload)?

Thanks!

**Reply by mohsenbostan** [reply]
For the past month, I have struggled with this issue.

I hope these images are helpful

![image](https://user-images.githubusercontent.com/20592417/144318940-83a8e129-b806-4407-a97c-a3faf90dda55.png)


![image](https://user-images.githubusercontent.com/20592417/144318422-1ad7e1a2-21ae-47be-bec2-f0f0cc3a04f4.png)

**Reply by joshhanley** [reply]
@mohsenbostan thanks!

Hmm yeah something there isn't right, if you have a look at the first screenshot, at the `Response Headers > Content-Type` you can see it says `text/html` but it should say `application/json`, see my screenshot below.

Something is changing the response to an incorrect type. Not sure if thats an issue with the nginx config or whether something in Laravel might be doing it.

![image](https://user-images.githubusercontent.com/882837/144342813-a4219bc1-bdfa-4c63-b439-77654b6ed95e.png)

**Reply by mohsenbostan** [reply]
So how should I fix this ? any way to debug it ?

**Reply by joshhanley** [reply]
@mohsenbostan honestly, I'm not exactly sure.

I think you're going to have to do some digging to try and find out what is causing the response to change and narrow down whether it is a server issue or a Laravel issue first. 

You could probably try putting some logging in Laravel as to the response type it is sending, so you can review them all and see if it changes. That would at least narrow it down to whether it's Laravel causing the problem or not.

Hope this helps!

**Comment by besrabasant** [comment]
I am also facing the same issue.

**Comment by silnarm** [comment]
While it seems bizarre that this doesn't just happen straight away, I have a feeling this is ultimately Livewire's fault:
![image](https://user-images.githubusercontent.com/549422/153731686-9040ddbf-c882-4476-91a0-712e9f4ed066.png)

js/connection/index.js :
![image](https://user-images.githubusercontent.com/549422/153731776-ce0996b5-3f06-4c54-b95c-a7a4bb8c0793.png)

I can't get Apache to do it, but I suspect Nginx is just trying to conform to the request.
I'm not installing nginx to try though, anyone who can replicate this reliably able to test this out? @mohsenbostan @besrabasant
[For testing purposes I think just modifying it in ./vendor/livewire/livewire/dist/livewire.js.map is fine, but please don't tell anyone I said that ;-)]

**Reply by joshhanley** [reply]
@silnarm yeah I'm running nginx without that issue and can't replicate it either.

@mohsenbostan or @besrabasant can you share your nginx config as well as what server OS you are using? Also are you building your servers with Forge or anything like that?

**Reply by seiyan0922** [reply]
@joshhanley 

Hi!
Sorry for participating in the old story
I am also facing the same issue.

My environment is as follows, do you know anything?

### docker-compose.yml

```
version: '3'

networks:
  app_network:
    external: true
services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - INSTALL_XDEBUG=true
    volumes:
      - ./src:/var/www
    networks:
      - app_network
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - 8000:80
    entrypoint: >
      /bin/sh -c '
      sed -i "s/127.0.0.1/dd-agent/g" /etc/nginx/dd-config.json &&
      sed -i "s/127.0.0.1/php-fpm/g" /etc/nginx/conf.d/client.conf &&
      nginx -g "daemon off;"
      '
    networks:
      - app_network
```

### Dockerfile

```
# An nginx container that includes the module and plugin required for Datadog tracing.
FROM nginx:1.19.2

ARG NGINX_VERSION=1.19.2

RUN apt-get update && \
  apt-get install -y wget tar

# Install nginx-opentracing
RUN get_latest_release() { \
  wget -qO- "https://api.github.com/repos/$1/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'; \
  } && \
  NGINX_VERSION=`nginx -v 2>&1 > /dev/null | sed -E "s/^.*nginx\/(.*)/\\1/"`&& \
  OPENTRACING_NGINX_VERSION="$(get_latest_release opentracing-contrib/nginx-opentracing)" && \
  DD_OPENTRACING_CPP_VERSION="$(get_latest_release DataDog/dd-opentracing-cpp)" && \
  \
  wget https://github.com/opentracing-contrib/nginx-opentracing/releases/download/${OPENTRACING_NGINX_VERSION}/linux-amd64-nginx-${NGINX_VERSION}-ot16-ngx_http_module.so.tgz && \
  NGINX_MODULES=$(nginx -V 2>&1 | grep "configure arguments" | sed -n 's/.*--modules-path=\([^ ]*\).*/\1/p') && \
  tar zxvf linux-amd64-nginx-${NGINX_VERSION}-ot16-ngx_http_module.so.tgz -C "${NGINX_MODULES}" && \
  # Install Datadog module
  wget -O - https://github.com/DataDog/dd-opentracing-cpp/releases/download/${DD_OPENTRACING_CPP_VERSION}/linux-amd64-libdd_opentracing_plugin.so.gz | gunzip -c > /usr/local/lib/libdd_opentracing_plugin.so

RUN rm /etc/nginx/conf.d/*

COPY ./docker/nginx/config/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/config/dd-config.json /etc/nginx/dd-config.json
COPY ./docker/nginx/config/conf.d/ /etc/nginx/conf.d
COPY ./src /var/www/

EXPOSE 80
```
