### DISCUSSION TITLE
Uncaught (in promise) SyntaxError: Unexpected token { in JSON at position  at JSON.parse

### DISCUSSION THREAD

**Discussion by besrabasant** [livewire/livewire#4656] [7. Bugs (archived)]
My livewire components run without any issue in `local`, but when I deploy my component in `production` I get back a malformed response from livewire components.

```json
{
    "fingerprint": {
        "id": "KYV25GwdqoTFQr5EddGU",
        "name": "modals",
        "locale": "en",
        "path": "admin",
        "method": "GET",
        "v": "acj"
    },
    "serverMemo": {
        "children": {
            "time-slots.create": {
                "id": "y3QDrKj2bHdQmSGIPENa",
                "tag": "div"
            }
        },
        "errors": [],
        "htmlHash": "697abe6e",
        "data": {
            "alias": "time-slots.create",
            "params": []
        },
        "dataMeta": [],
        "checksum": "cad37274f5d7f8c1c0250831b9d0a864fcd3bf6218d93be67fa20e6f9304cc37"
    },
    "updates": [
        {
            "type": "fireEvent",
            "payload": {
                "id": "09y1",
                "event": "resetModal",
                "params": []
            }
        }
    ]
}{
    "effects": {
        "html": "<div wire:id=\"KYV25GwdqoTFQr5EddGU\" id=\"laravel-livewire-modals\" tabindex=\"-1\"\n    data-bs-backdrop=\"static\" data-bs-keyboard=\"false\"\n    wire:ignore.self class=\"modal fade\">\n\n    \n<\/div>\n",
        "dirty": [
            "alias"
        ]
    },
    "serverMemo": {
        "children": [],
        "htmlHash": "da499807",
        "data": {
            "alias": null
        },
        "checksum": "d1770a027156167e341540ed556a5e0a2553990c657d6934de3b4c9802d6cd98"
    }
}
```

Is there something wrong with my setup? Have I missed something?

**Comment by joshhanley** [comment]
@besrabasant did you manage to sort this out? If not, some more details about your local setup vs production setup would be good. What OS's, web server, php version, etc. are you using? Also are you using Forge or anything for server setup?

Thanks!

**Reply by seiyan0922** [reply]
@joshhanley 

Hi!
Sorry for participating in the old story
I am also facing the same issue.

My environment is as follows, do you know anything?

### docker-compose.yml

```
version: '3'

networks:
  app_network:
    external: true
services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - INSTALL_XDEBUG=true
    volumes:
      - ./src:/var/www
    networks:
      - app_network
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - 8000:80
    entrypoint: >
      /bin/sh -c '
      sed -i "s/127.0.0.1/dd-agent/g" /etc/nginx/dd-config.json &&
      sed -i "s/127.0.0.1/php-fpm/g" /etc/nginx/conf.d/client.conf &&
      nginx -g "daemon off;"
      '
    networks:
      - app_network
```

### Dockerfile

```
# An nginx container that includes the module and plugin required for Datadog tracing.
FROM nginx:1.19.2

ARG NGINX_VERSION=1.19.2

RUN apt-get update && \
  apt-get install -y wget tar

# Install nginx-opentracing
RUN get_latest_release() { \
  wget -qO- "https://api.github.com/repos/$1/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'; \
  } && \
  NGINX_VERSION=`nginx -v 2>&1 > /dev/null | sed -E "s/^.*nginx\/(.*)/\\1/"`&& \
  OPENTRACING_NGINX_VERSION="$(get_latest_release opentracing-contrib/nginx-opentracing)" && \
  DD_OPENTRACING_CPP_VERSION="$(get_latest_release DataDog/dd-opentracing-cpp)" && \
  \
  wget https://github.com/opentracing-contrib/nginx-opentracing/releases/download/${OPENTRACING_NGINX_VERSION}/linux-amd64-nginx-${NGINX_VERSION}-ot16-ngx_http_module.so.tgz && \
  NGINX_MODULES=$(nginx -V 2>&1 | grep "configure arguments" | sed -n 's/.*--modules-path=\([^ ]*\).*/\1/p') && \
  tar zxvf linux-amd64-nginx-${NGINX_VERSION}-ot16-ngx_http_module.so.tgz -C "${NGINX_MODULES}" && \
  # Install Datadog module
  wget -O - https://github.com/DataDog/dd-opentracing-cpp/releases/download/${DD_OPENTRACING_CPP_VERSION}/linux-amd64-libdd_opentracing_plugin.so.gz | gunzip -c > /usr/local/lib/libdd_opentracing_plugin.so

RUN rm /etc/nginx/conf.d/*

COPY ./docker/nginx/config/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/config/dd-config.json /etc/nginx/dd-config.json
COPY ./docker/nginx/config/conf.d/ /etc/nginx/conf.d
COPY ./src /var/www/

EXPOSE 80
```
