### DISCUSSION TITLE
Livewire V3 - Nprogress bar customization

### DISCUSSION THREAD

**Discussion by ev3rlost** [livewire/livewire#5830] [1. Help] [answered]
How can we change the color of the loading bar (and spinner) using Tailwind (or vanilla CSS)? I haven't found anything in the Livewire 3 docs (it doesn't even mention it's using the Nprogress.js library). Do we need to import the CSS file manually or can we just override it with !important?

**Comment by ev3rlost** [comment, marked as answer]
Found the solution as soon as I posted the question. For anyone wondering, just override it with !important (vanilla CSS or in the app.css file using Tailwind).

```css
#nprogress .bar {
    background: red !important;
}
#nprogress .spinner-icon {
    border-top-color: red !important;
    border-left-color: red !important;
}
```
