### DISCUSSION TITLE
Navigate: Page loading indicator not working

### DISCUSSION THREAD

**Discussion by tahirafridi** [livewire/livewire#6569] [7. Bugs (archived)] [answered]
### Livewire version

v3.0.1

### Which PHP version are you using?

PHP 8.2

### Steps To Reproduce

The anchors with wire:navigate should show the progress/loading indicator on the page top section as we see in the every SPA websites for example on YouTube
I've checked config/livewire.php file and I found this feature is enabled by default, but still can't see the loading indicator on page top section

`
'navigate' => [
        'show_progress_bar' => true,
],
`

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I have provided code samples as text and NOT images.
- [X] I understand my bug report will be removed if I haven't met the criteria above.

**Comment by N1ebieski** [comment, marked as answer]
Check the "z-index" property.

I had to increase "z-index" because bootstrap's navbar obscured a progress bar.


```scss
#nprogress {
    .bar {
        z-index: 2000 !important;
    }

    .spinner {
        z-index: 2000 !important;        
    }
}
```
