### DISCUSSION TITLE
Response::assertSeeLivewire does not exist in ci\cd testing

### DISCUSSION THREAD

**Discussion by Okatsumo** [livewire/livewire#8358] [1. Help] [answered]
Tests for basic livewire components in ci\cd github are not working for me, but tests are running locally.

PHPUnit output ci\cd:
```
8) Tests\Feature\ProfileTest::test_profile_page_is_displayed
BadMethodCallException: Method Illuminate\Http\Response::assertSeeLivewire does not exist.

/home/runner/work/osu-tap/osu-tap/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:112
/home/runner/work/osu-tap/osu-tap/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:1806
/home/runner/work/osu-tap/osu-tap/vendor/livewire/volt/src/VoltServiceProvider.php:119
/home/runner/work/osu-tap/osu-tap/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:123
/home/runner/work/osu-tap/osu-tap/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:1803
/home/runner/work/osu-tap/osu-tap/tests/Feature/ProfileTest.php:22
/home/runner/work/osu-tap/osu-tap/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:61
```

Workflow:
```
  tests:
    name: Run PHPUnit/Feature tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: osutap
          MYSQL_ROOT_PASSWORD: forge
          MYSQL_PASSWORD: forge
          MYSQL_USER: forge
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install -n --prefer-dist --no-progress --ansi && composer info

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          sed -i 's/CACHE_DRIVER=redis/CACHE_DRIVER=file/' .env
          sed -i 's/SESSION_DRIVER=redis/SESSION_DRIVER=file/' .env
          php artisan key:generate
          php artisan migrate

      - name: Run building frontend
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: |
          npm install
          npm run build
          echo $(ls ./public/build)

      - name: Run Unit tests
        env:
          APP_ENV: local
          RUNNING_IN_CI: true
        run: |
          vendor/bin/phpunit --testsuite Unit

      - name: Run Feature tests
        env:
          APP_ENV: local
          RUNNING_IN_CI: true
        run: |
          vendor/bin/phpunit --testsuite Feature

```
