### ISSUE TITLE
Reusable Blade Modal

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#180]
So, I recently created an issue (#179), because I was not able to use `wire:` syntax inside a Vue component. For my specific case, I was using a VueJS modal component and wanted to use the `wire:` syntax inside this component.

As @calebporzio wrote:

> When Livewire is crawling the DOM, if it encounters a Vue component, it will skip it's contents.
> This is because Livewire AND Vue can't co-exist in that way. They both want control of the DOM. So Livewire gives up control of the DOM of any Vue component.
> I recommend you use Blade for a modal component.

The reason for using Vue-js-modal package was just to create a simple modal. Nothing else. I can imagine that a lot of other people simply just want to be able to create a simple modal.

This is my approach to creating a reusable modal, using LiveWire and Blade.

First I start by creating a LiveWire component:

```
php artisan make:livewire partials.modal
```

Then inside the component class, `Modal.php`, I have below:

```php
public $isOpen = false;
protected $listeners = ['toggleModal' => 'toggle'];

public function toggle()
{
    if ($this->isOpen) {
        $this->isOpen = false;
    } else {
        $this->isOpen = true;
    }
}

public function render()
{
    return view('livewire.partials.modal');
}
```
Inside the Blade view, this is what I currently have:

```html
<div>
    <div
        class="modal h-full w-full absolute bottom-0 top-0 left-0 right-0 z-50 bg-gray-100 p-4 @if($isOpen) show @endif"
        id="modal">
        <div class="modal-dialog w-1/3 p-4 rounded">
            Modal content here
        </div>

    </div>
</div>
```

Above utilizes TailwindCSS, however I have written some custom CSS as well:

```css
/* Start Component: Modal */
.modal {
    @apply fixed top-0 bottom-0 left-0 right-0 w-full h-full opacity-0 hidden;
    -webkit-transition: opacity 100ms ease-in;
    -moz-transition: opacity 100ms ease-in;
    transition: opacity 100ms ease-in;
    background: rgba(0, 0, 0, 0.8);

    &.show {
        @apply opacity-100 block;
        pointer-events: auto !important;
        background: rgba(0, 0, 0, .60);
    }

    .modal-dialog {
        position: relative;
        margin: 10% auto;
        @apply bg-white shadow;
    }
}
```

The above will render:

[![Example modal][1]][1]

  [1]: https://i.stack.imgur.com/i6CB4.png

I have added below custom javascript, so when an user clicks *outside* the modal, it will call the `toggleModal` method and hide the modal accordingly.

`modal.js` 
```javascript
(function () {
    const modal = document.getElementById("modal");
    modal.addEventListener("click", function (e) {
        //Only toggleModal if the click is outside the modal area.
        if (e.target !== this)
            return;
        //Emit the event to toggle the modal.
        window.livewire.emit('toggleModal')
    }, false);

})();
```

# Where to go from here?

**Make the modal reusable**.

As it is right now, I cannot reuse the modal component, because the actual content of the modal, will have to be updated in the view file `partials.modal.blade.php`.

I am not quite sure if it's possible to even make it reusable and allow for it to have some sort of custom content?

For example:

```html
//Parent view:
@livewire('partials.modal')
@section('modal')
   Dynamic content in here.
@endsection

//Modal view
<div>
    <div
        class="modal h-full w-full absolute bottom-0 top-0 left-0 right-0 z-50 bg-gray-100 p-4 @if($isOpen) show @endif"
        id="modal">
        <div class="modal-dialog w-1/3 p-4 rounded">
            @yield('modal')
        </div>
    </div>
</div>
```

Above does not work, however. Does anyone have any ideas?

**Please note:** I hope this kind of post is allowed here, Caleb. If not, please let me know and I'll remove it.
